// Conceptors Animal Health LLC - Standalone Medical Representative CRM Master Data
// Distribution for Catalysis Spain, BARD Czech, Vitasigna, and Ringbio across the UAE

window.INITIAL_PRODUCTS = [
  // CATALYSIS SPAIN
  { code: 'AS030', id: 'CAT-01', brand: 'CATALYSIS', name: 'ASBRIP 30 ml', unitPrice: 32, currentStock: 4279, category: 'Respiratory / Immunity' },
  { code: 'AS150', id: 'CAT-02', brand: 'CATALYSIS', name: 'ASBRIP 150 ml', unitPrice: 104, currentStock: 190, category: 'Respiratory / Immunity' },
  { code: 'CA030', id: 'CAT-03', brand: 'CATALYSIS', name: 'CARMINAL 30 ml', unitPrice: 38, currentStock: 1260, category: 'Gastrointestinal' },
  { code: 'CA150', id: 'CAT-04', brand: 'CATALYSIS', name: 'CARMINAL 150 ml', unitPrice: 118, currentStock: 78, category: 'Gastrointestinal' },
  { code: 'KR030', id: 'CAT-05', brand: 'CATALYSIS', name: 'KARDIOLI 30 ml', unitPrice: 34, currentStock: 116, category: 'Cardiovascular' },
  { code: 'KR150', id: 'CAT-06', brand: 'CATALYSIS', name: 'KARDIOLI 150 ml', unitPrice: 114, currentStock: 31, category: 'Cardiovascular' },
  { code: 'FO030', id: 'CAT-07', brand: 'CATALYSIS', name: 'FOLREX 30 ml', unitPrice: 32, currentStock: 320, category: 'Joints / Mobility' },
  { code: 'FO150', id: 'CAT-08', brand: 'CATALYSIS', name: 'FOLREX 150 ml', unitPrice: 112, currentStock: 44, category: 'Joints / Mobility' },
  { code: 'KA030', id: 'CAT-09', brand: 'CATALYSIS', name: 'KALSIS 30 ml', unitPrice: 32, currentStock: 307, category: 'Bone & Calcium' },
  { code: 'KA150', id: 'CAT-10', brand: 'CATALYSIS', name: 'KALSIS 150 ml', unitPrice: 104, currentStock: 32, category: 'Bone & Calcium' },
  { code: 'OB030', id: 'CAT-11', brand: 'CATALYSIS', name: 'OBEX 30 ml', unitPrice: 38, currentStock: 328, category: 'Metabolism / Weight' },
  { code: 'OB150', id: 'CAT-12', brand: 'CATALYSIS', name: 'OBEX 150 ml', unitPrice: 125, currentStock: 17, category: 'Metabolism / Weight' },
  { code: 'RE030', id: 'CAT-13', brand: 'CATALYSIS', name: 'RENALOF 30 ml', unitPrice: 32, currentStock: 1961, category: 'Renal / Urinary' },
  { code: 'RE150', id: 'CAT-14', brand: 'CATALYSIS', name: 'RENALOF 150 ml', unitPrice: 104, currentStock: 278, category: 'Renal / Urinary' },
  { code: 'VP030', id: 'CAT-15', brand: 'CATALYSIS', name: 'VIUSID 30 ml', unitPrice: 40, currentStock: 2676, category: 'Immunostimulant & Antiviral' },
  { code: 'VP150', id: 'CAT-16', brand: 'CATALYSIS', name: 'VIUSID 150 ml', unitPrice: 115, currentStock: 235, category: 'Immunostimulant & Antiviral' },
  { code: 'OC030', id: 'CAT-17', brand: 'CATALYSIS', name: 'OCOXIN 30 ml', unitPrice: 42, currentStock: 259, category: 'Oncology / Antioxidant' },
  { code: 'OC150', id: 'CAT-18', brand: 'CATALYSIS', name: 'OCOXIN 150 ml', unitPrice: 131, currentStock: 12, category: 'Oncology / Antioxidant' },
  { code: 'VA030', id: 'CAT-19', brand: 'CATALYSIS', name: 'VUISID AVIS 30 ml', unitPrice: 40, currentStock: 293, category: 'Avian Immunity' },
  { code: 'VA150', id: 'CAT-20', brand: 'CATALYSIS', name: 'VUISID AVIS 150 ml', unitPrice: 110, currentStock: 39, category: 'Avian Immunity' },
  { code: 'VD030', id: 'CAT-21', brand: 'CATALYSIS', name: 'VUISID DETOX 30 ml', unitPrice: 40, currentStock: 599, category: 'Hepatic Detox' },
  { code: 'VD150', id: 'CAT-22', brand: 'CATALYSIS', name: 'VIUSID DETOX 150 ml', unitPrice: 115, currentStock: 48, category: 'Hepatic Detox' },
  { code: 'BC150', id: 'CAT-23', brand: 'CATALYSIS', name: 'BLUE CAP SHAMPOO PETS 150 ml', unitPrice: 55, currentStock: 324, category: 'Dermatology' },
  { code: 'BC400', id: 'CAT-24', brand: 'CATALYSIS', name: 'BLUE CAP SHAMPOO PETS 400 ml', unitPrice: 110, currentStock: 43, category: 'Dermatology' },

  // BARD CZECH
  { code: 'BE005', id: 'BRD-01', brand: 'BARD', name: 'BARD Clever Fungus Ecosin 5x3g', unitPrice: 77, currentStock: 656, category: 'Antifungal / Derm' },
  { code: 'BD0100', id: 'BRD-02', brand: 'BARD', name: 'BARD Clever Fungus Dermasine 100ml', unitPrice: 76, currentStock: 351, category: 'Antifungal / Derm' },
  { code: 'BVO50', id: 'BRD-03', brand: 'BARD', name: 'BARD Pythie Pets vet ointment 50ml', unitPrice: 58, currentStock: 463, category: 'Dermatology' },
  { code: 'BFB00', id: 'BRD-04', brand: 'BARD', name: 'BARD Pythie Pets Fresh Breath', unitPrice: 53, currentStock: 365, category: 'Oral Care' },
  { code: 'BPE00', id: 'BRD-05', brand: 'BARD', name: 'BARD Pythie Pets Ear cleaner', unitPrice: 58, currentStock: 317, category: 'Ear Care' },

  // VITASIGNA
  { code: 'VR030', id: 'VIT-01', brand: 'VITASIGNA', name: 'VIRULYS Paste 30ml', unitPrice: 33, currentStock: 2039, category: 'Feline Lysine / Immunity' },

  // RINGBIO RAPID TESTS
  { code: 'TOX015', id: 'RING-01', brand: 'RINGBIO', name: 'Toxoplasma Antibody Rapid 15 Test Card', unitPrice: 270, currentStock: 45, category: 'Diagnostics' },
  { code: 'CPV015', id: 'RING-02', brand: 'RINGBIO', name: 'Canine Parvovirus (CPV) 15 Test Card', unitPrice: 225, currentStock: 60, category: 'Diagnostics' },
  { code: 'FPV015', id: 'RING-03', brand: 'RINGBIO', name: 'Feline Panleukopenia Virus (FPV) 15 Test Card', unitPrice: 225, currentStock: 55, category: 'Diagnostics' }
];

window.INITIAL_SENIOR_MANAGERS = [
  { id: 'MGR-01', name: 'Dr. Sameh Ageez', role: 'Senior Sales Manager UAE', email: 'sameh.ageez@conceptors.ae', phone: '+971 50 888 9900', active: true },
  { id: 'MGR-02', name: 'Ms. Reem Al-Falasi', role: 'Commercial & Operations Director', email: 'commercial@conceptors.ae', phone: '+971 52 444 3322', active: true }
];

window.INITIAL_USERS = [
  {
    username: 'shaimaa.t1',
    password: 'rep1',
    name: 'Dr. Shaimaa',
    title: 'Medical Representative - Territory 1',
    role: 'rep_t1',
    territory: 'T1',
    email: 'shaimaa.t1@conceptors.ae',
    phone: '+971 50 123 4567',
    avatar: 'SH',
    color: '#38bdf8'
  },
  {
    username: 'ahmed.t1', // alias
    password: 'rep1',
    name: 'Dr. Shaimaa',
    title: 'Medical Representative - Territory 1',
    role: 'rep_t1',
    territory: 'T1',
    email: 'shaimaa.t1@conceptors.ae',
    phone: '+971 50 123 4567',
    avatar: 'SH',
    color: '#38bdf8'
  },
  {
    username: 'marsel.t2',
    password: 'rep2',
    name: 'Dr. Marsel',
    title: 'Medical Representative - Territory 2',
    role: 'rep_t2',
    territory: 'T2',
    email: 'marsel.t2@conceptors.ae',
    phone: '+971 55 987 6543',
    avatar: 'MR',
    color: '#c084fc'
  },
  {
    username: 'youssef.t2', // alias
    password: 'rep2',
    name: 'Dr. Marsel',
    title: 'Medical Representative - Territory 2',
    role: 'rep_t2',
    territory: 'T2',
    email: 'marsel.t2@conceptors.ae',
    phone: '+971 55 987 6543',
    avatar: 'MR',
    color: '#c084fc'
  },
  {
    username: 'sameh.ageez',
    password: 'admin',
    name: 'Dr. Sameh Ageez',
    title: 'Senior Sales Manager UAE',
    role: 'manager',
    territory: 'ALL',
    email: 'sameh.ageez@conceptors.ae',
    phone: '+971 50 888 9900',
    avatar: 'SA',
    color: '#10b981'
  },
  {
    username: 'manager', // alias
    password: 'admin',
    name: 'Dr. Sameh Ageez',
    title: 'Senior Sales Manager UAE',
    role: 'manager',
    territory: 'ALL',
    email: 'sameh.ageez@conceptors.ae',
    phone: '+971 50 888 9900',
    avatar: 'SA',
    color: '#10b981'
  }
];

window.INITIAL_REPS = [
  { 
    id: 'T1', 
    name: 'Shaimaa', 
    title: 'Medical Representative - Territory 1',
    territory: 'T1', 
    emirates: ['Dubai', 'Abu Dhabi', 'Al Ain'], 
    phone: '+971 50 123 4567', 
    email: 'shaimaa.t1@conceptors.ae', 
    monthlyTargetCalls: 100, 
    color: '#38bdf8',
    avatar: 'SH'
  },
  { 
    id: 'T2', 
    name: 'Marsel', 
    title: 'Medical Representative - Territory 2',
    territory: 'T2', 
    emirates: ['Sharjah', 'Ajman', 'Ras al- Khaimah', 'Fujairah', 'Umm al- Quwain'], 
    phone: '+971 55 987 6543', 
    email: 'marsel.t2@conceptors.ae', 
    monthlyTargetCalls: 100, 
    color: '#c084fc',
    avatar: 'MR'
  }
];

window.INITIAL_CUSTOMERS = [
  // Territory 1 (Dubai, Abu Dhabi, Al Ain) - Assigned to Shaimaa (123 Accounts)
  { code: 'DC0678', name: 'PRIME PAWS VET CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0277', name: 'ANIMAL SPECIALIST CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0339', name: 'DOCTOR DOLITTLE VETERINARY CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0615', name: 'INTERVET VETERINARY CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0835', name: 'PETS REPUBLIC VETERINARY CLINIC', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0870', name: 'HAPPY PETS VETERINARY CLINIC', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0321', name: 'HEALTH AND CARE VETERINARY CLINIC', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0636', name: 'THE CITY VET CLINIC MEYDAN BR.', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0721', name: 'TOP CARE VETERINARY CLINIC', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0618', name: 'PERFECT DOSE VET CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AP0892', name: 'EUROGULF ANIMAL AND BIRDS FOOD TRADING', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0681', name: 'THE HILLS VET CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0406', name: 'JABAL ALADHAM VETERINARY CLINIC', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0551', name: 'THE CITY VET CLINIC AL WARQA', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0767', name: 'PET STREET VET CLINIC', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0411', name: 'JVC EXPRESS VETERINARY CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0630', name: 'Liberty veterinary clinic', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0310', name: 'CANADIAN VETRINARY CLINIC - AL MEENA', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0658', name: 'SWISS VETERINARY CLINIC LLC O.P.C', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0322', name: 'CLOUD 9 PET HOTEL AND CARE', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0478', name: 'PETS HEALTH VETERINARY CLINIC FZE', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0050', name: 'AL FALAH VETERINARY CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0494', name: 'PURE LIFE VET TREATMENT', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0631', name: 'Majestic vet clinic', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0626', name: '2FEET4PAWS (& EXOTICS) VETERINARY CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0885', name: 'PAWBULANCE VETERINARY CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0738', name: 'Eleven Eleven Vet Clinic', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0620', name: 'AMORE VETERINARY CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0460', name: 'NEW VETERINARY CLINIC', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0550', name: 'THE CITY VET CLINIC (JVT BRANCH)', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NP0231', name: 'ALNASR VETERINARY EST', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0427', name: 'MARINA VET CLINIC L.L.C', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0304', name: 'BRITISH VETERINARY CENTRE LLC KHALIFA CITY', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0880', name: 'KINGS VET CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0771', name: 'SKY VET CLINIC', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0648', name: 'LIFE LINE VET CLINIC', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0910', name: 'MARSHAL VET CLINIC', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0908', name: 'MYPETSFIRST VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0871', name: 'MIKE\'S VET', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AP0289', name: 'BAGHDAD VETERINARY MEDICINE ESTABLISHMENT- BRANCH 1', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0616', name: 'PET YARD VET CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0584', name: 'VETS FUR PETS VETERINARY CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0575', name: 'VET VETERINARY CLINIC TOWN SQ', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0650', name: 'ANUBIS VET CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0918', name: 'SAFE CARE VETERINARY CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0657', name: 'VETS IN THE CITY', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0920', name: 'THE ARK ANIMAL CLINIC - FZCO', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0549', name: 'THE CITY VET CLINIC (AL BARSHA BRANCH)', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0905', name: 'TOP VET VETERINARY CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0506', name: 'ROYAL VETERINARY CENTRE', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0922', name: 'MYPETSFIRST VETERINARY CLINIC (BR)', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0553', name: 'THE CITY VET CLINIC MIRDIF', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0482', name: 'PETS OASIS VET CLINIC AUH', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0800', name: 'PETOLOGY VET CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0925', name: 'CATS MEDICAL CENTER VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0319', name: 'CITY VET VETERINERY CLINIC AL AIN', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0926', name: 'VETS FOR PETS L.L.C', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AP0705', name: 'AL RAHA FOR VETERIANRY TREATMENT', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0883', name: 'KARE VETERINARY CLINIC LLC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0617', name: 'PET AVENUE JVC CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0714', name: 'PET PAVILLON', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0931', name: 'PETLAND WELLNESS VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0932', name: 'TERRITORY VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0574', name: 'VET VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0935', name: 'WELLPET VETERINARY CLINIC. L.L.C -O.P.C', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0139', name: 'AL RAWDAH VETERINARY CLINIC', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0823', name: 'AL FALAH VETERINARY CLINIC AL MEENA BRANCH', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0878', name: 'PURE LIFE VET TREATMENT DUBAI BRANCH', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0778', name: 'PETS SOCIETY VETERINARY CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0937', name: 'ALEX VETERINARY CLINIC - L.L.C - O.P.C', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0938', name: 'FAMILY VETERINARY CLINIC - L.L.C - O.P.C', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0484', name: 'PETZONE VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0468', name: 'PAWS AND CLAWS VETERINARY CLINIC', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0729', name: 'PAWS & CLAWS VET CLINIC JVC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0941', name: 'HILAL VETERINARY CENTER - L.L.C - S.P.C', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0940', name: 'FAIRY TAIL VETERINARY CLINIC L.L.C.', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0942', name: 'VIP VETERINARY CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AP0773', name: 'BAYT AL TYOOR VET PH', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0459', name: 'NATIONAL VETERINARY CLINIC L.L.C', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0660', name: 'AL RAHA VET CLINIC', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0825', name: 'CARDIOVET VETERINARY CLINIC LLC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0945', name: 'R P C VETERINARY CLINIC LLC', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0623', name: 'PETS HAVEN VET CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0711', name: 'AL TUHAMY VETERINARY CLINIC', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AP0306', name: 'BU HAREB VETRINARY MEDICINE ESTAB', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AP0147', name: 'AL REHAB VETERINARY PHARMACY', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AP0833', name: 'AL GHAZAL VETERINARY PHARMACY', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AP0890', name: 'F3 FALCON FOR ANIMAL AND BIRDS FOOD TRADING', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AP0949', name: 'MATYT ALSABOOQ FOR VETERINARY MEDICINE AND EQUIPMENT - L.L.C -O.P.C', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0743', name: 'AL FATEH VET CLINIC', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0455', name: 'NAJM SUHAIL VETERINERY CLINIC', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0308', name: 'CANADIAN VETERINARY CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NP761', name: 'AL FALAH VET - L.L.C - S.P.C - BRANCH', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AP0955', name: 'AL QEMMA ANIMAL AND POULTRY FOOD - L.L.C - S.P.C', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0957', name: 'Kings Veterinary Clinic L.L.C', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AP0708', name: 'WELLFARE VETERINARY CLINIC', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0958', name: 'PAWSITIVE VIBES VETERINARY CLINIC LLC- S.P.C', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0961', name: 'Animal Planet Veterinary Clinic', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AP0775', name: 'AL JOOD PH', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0278', name: 'ANIMALIA VETERINARIAN TREATMENT L.L.C', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0747', name: 'HOPE VETERINARY CLINIC', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0765', name: 'PETS OASIS', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC0963', name: 'Soul Veterinary Clinic - Al Ain Branch', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0461', name: 'NOBLE VETERINARY CLINIC DIP', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0972', name: 'PET WELL VETERINARY CLINIC', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0897', name: 'PET BOND VETERINARY CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0974', name: 'CASTLE VETERINARY CENTER -  L.L.C - S.P.C', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0900', name: 'AL FURJAN VET CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AP0978', name: 'BULBIN ANIMAL AND POULTRY FOOD LLC - SPC', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NP0048', name: 'AL FALAH VET. EST AL AIN', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0959', name: 'Aleef Veterinary Clinic - AUH', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AP0121', name: 'AL NAWADIR VET PHARMACY AUH CENTER', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0988', name: 'CIRCLE VET VETERINARY CLINIC - FZE', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0984', name: 'PROVETEX VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0991', name: 'PET PLANET VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0983', name: 'HORUS VETERINARY TREATMENT', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0996', name: 'VET POINT VETERINARY CLINIC L.L.C S.O.C', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0998', name: 'ALPHAPET VETERINARY CLINIC LLC', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0637', name: 'VET PLUS MARINA', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC1001', name: 'ZOOVET VETERING CLINIC', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'NC1002', name: 'FIT PAWS PETS CLINIC', location: 'Al Ain', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0689', name: 'PET FIRST VET CLINIC', location: 'Dubai', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'AC0992', name: 'AL REEM VETERINARY CLINIC', location: 'Abu Dhabi', territory: 'T1', repId: 'T1', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },

  // Territory 2 (Northern Emirates) - Assigned to Marsel (137 Accounts)
  { code: 'FC0852', name: 'LOVELY PET CLINIC', location: 'Fujairah', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0826', name: 'AL FERSAN VETERINARY CLINIC', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RP0236', name: 'ALNOOR VETERINARY CLINIC', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JP0199', name: 'ALAADYAT VETERINARY MEDICINE', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0072', name: 'AL HAYAT VETERINARY CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0889', name: 'EASYVET VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DP0642', name: 'VETERINARIAN FOR VETERINARY MEDICINES', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RC0312', name: 'CANARY PET HUB CLINIC', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'UC0162', name: 'AL SALAMA VETERINARY CLINIC', location: 'Umm al- Quwain', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0340', name: 'DR SAMIR VET CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RC0471', name: 'PET CARE CLINIC', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0629', name: 'WINTERFELL VETERINARY CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0621', name: 'PET LAND VETERINARY CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0541', name: 'SYNERGY VETERINARY CLINIC LLC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0611', name: 'HAPPY TAILS VETERINARY CLINIC', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0821', name: 'Petflix Veterinary Clinic LLC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0624', name: 'Happy paws vet clinic', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0661', name: 'THE MOON VET CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0856', name: 'PET JOY VETERINARY CLINIC - FZCO', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0609', name: 'HUB VET CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0576', name: 'VETCARE VETRINARY MEDICAL CENTER', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RC0544', name: 'TAG VETERINARY CLINIC', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0749', name: 'ALALAMIA VETERINARY CLINIC', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RP0896', name: 'SHAMAL VETERINARY PHARMACY', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'FP0704', name: 'AL KAYAN VET PHARMACY', location: 'Fujairah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RC0022', name: 'AL ASIFAH VETERINARY CLINIC LLC', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RC0809', name: 'AL AMAL VET CLINIC', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0805', name: 'PET LIFE VET CLINIC', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RC0481', name: 'PETS OASIS VET CLINIC LLC, RAS AL KHAIMAH, UAE', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0613', name: 'AL JUBAIL VET CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0886', name: 'AL HEKMAH VET MEDICINES LLC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RC0497', name: 'RAS AL KHAIMAH VETERINARY CENTER', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0895', name: 'THE GREEN LINE VET CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0265', name: 'AL WATANYA VET CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0703', name: 'AL RAHMA VET CLINIC', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0307', name: 'CANADIAN VETERINARIAN CLINIC SHJ', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RC0806', name: 'CORNICHE VET CLINIC', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0903', name: 'THE PET DOCTOR CENTER', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0633', name: 'ROYAL PETS VETERINARY CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RP0115', name: 'AL NAWADIR VET PHARMACY RAK', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0901', name: 'THE PEARL VETERINARY CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0917', name: 'SUPER VET PET CLINIC LLC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0887', name: 'ALEF & ANEQ VETERINARY CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0122', name: 'AL NAWADIR VETRINARY MEDICINES & EQUIPMENT L.L.C', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0921', name: 'AL UMARA VETERINARIAN CLINIC L.L.C. SP', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'FC0840', name: 'AL-RAYAH AL-BAYDAA VET CLINIC', location: 'Fujairah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0077', name: 'AL JAWAREH VET CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'FC0912', name: 'ALRAYAH ALBAYDAA VET. CLINIC BR. 1', location: 'Fujairah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SP0228', name: 'ALMUMTAZ VET. MEDICINE', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0632', name: 'DEIRA VETERINARY CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0819', name: 'PET PALACE VETERINARY CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0766', name: 'AL RAYAN VET CLINIC LLC', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0445', name: 'MODERN VET L.L.C (JVC BR.)', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0737', name: 'CUTE CAT VETERINARY CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0475', name: 'PET LOVERS VETERINARY CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'FC0483', name: 'PETS,N US VETERINARY CLINIC', location: 'Fujairah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0927', name: 'JUNGLE VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0928', name: 'PET PULSE EMERGENCY VETERINARY CLINIC - FZCO', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0929', name: 'ZOKO VETERINARY CLINIC L.L.C', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0930', name: 'SUKAR PETS CARE AND VET', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0644', name: 'ZAD VET CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JP0843', name: 'VET LIFE PHARMACY', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'FC0911', name: 'CUTE PAWS VETERINARY CLINIC LLC', location: 'Fujairah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'FC0849', name: 'DAR AL WAAD VET CLINIC', location: 'Fujairah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0735', name: 'AL MALAKIYA VET CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0820', name: 'CROWN VETERINARY CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0933', name: 'PETS VETERINARY CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'FC0836', name: 'ALEEF VETERINARY CLINIC', location: 'Fujairah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0888', name: 'AL ANAMIL AL THAHABIA VET CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RC0936', name: 'DR. JIMMY VET CLINIC', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0939', name: 'PETBOOK VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0324', name: 'CREATURES WORLD VET CENTER', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0572', name: 'VET PLUS VET CENTER SHJ', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0943', name: 'AFDHAL VET.CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0639', name: 'MODERN VET DOWNTOWN', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0401', name: 'HARMONY VET CLINIC L.L.C', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0485', name: 'PHOENIX VETERINARY CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0638', name: 'SOUL VET CLINIC', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0947', name: 'AL AMIRAT CLINIC PETS CARE (S.P.S - L.L.C)', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RC0582', name: 'VETS24 VETERINARY CLINIC LLC', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0804', name: 'FLUFFY VETERINARY CLINIC FOR PETS', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0946', name: 'ANIMALIA VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0948', name: 'Eurogulf Animal & Birds Food Trading', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0951', name: 'PURR AND BARK PET VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DP0950', name: 'SINJAR VETERINARY MEDICINES TRADING', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RP0248', name: 'ALRAWAH VETERINARY PHARMACY', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0881', name: 'Sharjah Falconers Club Clinic', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'FC0952', name: 'Fluffy Cats Veterinary Clinic LLC - SPC', location: 'Fujairah', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0452', name: 'NAD AL SHIBA VETERINARY CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'FC0764', name: 'PETS HEALTH CARE VET CLINIC', location: 'Fujairah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0953', name: 'PAWS FAMILY VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0651', name: 'Pet Wellness vet clinic', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0875', name: 'AL TAREEK VET CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0954', name: 'TURKISH VET.CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0944', name: 'TERRITORY VETERINARY CLINIC L.L.C (BRANCH)', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0907', name: 'SHARJAH FALCON CLINIC LLC SOLE  PROPRIETORSHIP', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0956', name: 'PAW PRINTS VETERINARY CLINIC L.L.C', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0610', name: 'AlHayat Vetrinary Clinic', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'FC0855', name: 'VET CARE VET CLINIC', location: 'Fujairah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RC0587', name: 'VILLAGE VET LLC AL HAMRA MALL', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0476', name: 'PET POINT VETERINARY CLINIC FZCO', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0313', name: 'CANARY VET. CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RC0858', name: 'RAK ANIMAL WELFARE CENTER', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0906', name: 'PAWS SISTERS VETERINARY CLINIC LLC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0628', name: 'DUBAI MUNICIPALITY VET CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0964', name: 'ALENAYA PET CENTER', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0828', name: 'THE PET VET - VETERINARY', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DP0508', name: 'RUKAN ALZAJEL VETERINARY MEDICINES', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SP0117', name: 'AL NAWADIR MEDICINE AND VET. EQUIP SHJ', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0181', name: 'AL TAREK VETERINARY CLINIC L.L.C', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0087', name: 'AL MAHA VET CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'sc0307', name: 'CANADIAN VETERINARIAN CLINIC SHJ', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0971', name: 'CURE VETERINARY CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0969', name: 'CREEKSIDE VETERINARY CLINIC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0608', name: 'PUBLIC HEALTH DEPARTMENT THE VETERINARY CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DP0975', name: 'MODERN VET HOSPITAL LLC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0968', name: 'ELITE VET. CLINIC L.L.C', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0731', name: 'AL ASIFAH VET CLINIC SHJ', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0727', name: 'CITY PET VET CLINIC', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0976', name: 'Europets Care Veterinary Clinic LLC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'VIP Platinum', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0977', name: 'FOREVER PET CARE CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0979', name: 'EXPRESS VETERINARY CLINIC L.L.C', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0980', name: 'AL HAMRA VET CLINIC LLC. SP', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0981', name: 'AL HUDHUD VET CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'DC0982', name: 'DUBAI EQUINE HOSPITAL', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SP0831', name: 'VET PLUS MAIN OFFICE', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'dc0906', name: 'PAWS SISTERS VETERINARY CLINIC LLC', location: 'Dubai', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0985', name: 'FLUFFY VETERINARY CLINIC L L C - SHJ. BR 1', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0989', name: 'AL HAYAH PET CARE Clinic', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'JC0986', name: 'PET PARADISE VETERINARY CLINIC L.L.C', location: 'Ajman', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SP0990', name: 'SAHAM AL SHIFA VETERINARY MEDICINE TR LLC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'VIP Gold', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RC0994', name: 'Al MAHA VETERINARY CLINIC RAK', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'RC0993', name: 'JOLLY VET CLINIC', location: 'Ras al- Khaimah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0997', name: 'Kayan vet clinic', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'FC0999', name: 'Al Khoor Veterinary Clinic LLC', location: 'Fujairah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'SC0356', name: 'EURO PETS CLINIC', location: 'Sharjah', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
  { code: 'UC0479', name: 'PETS OASIS VETERINARY CLINIC - UAQ', location: 'Umm al- Quwain', territory: 'T2', repId: 'T2', tier: 'Silver', contactPerson: 'Lead Veterinarian', phone: '+971 4 000 0000' },
];

window.INITIAL_MONTHLY_PLANS = [
  {
    id: 'PLAN-2026-09-T1',
    repId: 'T1',
    repName: 'Shaimaa',
    year: 2026,
    month: 'SEP',
    targetVisits: 100,
    status: 'Approved',
    submittedAt: '2026-08-28T09:15:00Z',
    approvedAt: '2026-08-29T14:30:00Z',
    approvedBy: 'Dr. Sameh Ageez (Senior Sales Manager)',
    managerNotes: 'Approved. Focus heavily on Virulys 30ml feline launch and Renalof 150ml clinical clinic packs.'
  },
  {
    id: 'PLAN-2026-09-T2',
    repId: 'T2',
    repName: 'Marsel',
    year: 2026,
    month: 'SEP',
    targetVisits: 100,
    status: 'Approved',
    submittedAt: '2026-08-27T11:00:00Z',
    approvedAt: '2026-08-28T16:00:00Z',
    approvedBy: 'Dr. Sameh Ageez (Senior Sales Manager)',
    managerNotes: 'Approved. High coverage of BARD Dermasine across Sharjah and RAK.'
  },
  {
    id: 'PLAN-2026-10-T1',
    repId: 'T1',
    repName: 'Shaimaa',
    year: 2026,
    month: 'OCT',
    targetVisits: 100,
    status: 'Submitted',
    submittedAt: '2026-09-08T10:00:00Z',
    approvedAt: null,
    approvedBy: null,
    managerNotes: 'Submitted for Q4 commercial campaign review.'
  },
  {
    id: 'PLAN-2026-10-T2',
    repId: 'T2',
    repName: 'Marsel',
    year: 2026,
    month: 'OCT',
    targetVisits: 100,
    status: 'Draft',
    submittedAt: null,
    approvedAt: null,
    approvedBy: null,
    managerNotes: ''
  }
];

// Dual-Category Visits: Planned visits for a day + Unplanned visits submitted on that same day beside the planned ones
window.INITIAL_VISITS = [
  // ================= T1 (Shaimaa) September Historical Visits =================
  {
    id: 'VIS-2026-0901-01',
    repId: 'T1',
    clientCode: 'DC0340',
    clientName: 'DR SAMIR VET CLINIC',
    location: 'Dubai',
    date: '2026-09-01',
    timeSlot: 'Morning Round (09:00 - 10:30)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Samir Al-Khatib',
    doctorRole: 'Lead Veterinarian & Director',
    productsDetailed: ['VIRULYS Paste 30ml', 'VIUSID 30 ml'],
    doctorSentiment: 'Positive',
    samplesDropped: 1,
    sampleProduct: 'VIRULYS Paste 30ml',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Initial introduction of Virulys feline respiratory paste formulation',
    outcome: 'Introduced formulation data. Doctor requested small clinic trial before commercial order.',
    nextFollowUp: '2026-09-09',
    nextFollowUpPurpose: 'Review trial feedback'
  },
  {
    id: 'VIS-2026-0901-02',
    repId: 'T1',
    clientCode: 'DC0461',
    clientName: 'NOBLE VETERINARY CLINIC DIP',
    location: 'Dubai',
    date: '2026-09-01',
    timeSlot: 'Midday (11:30 - 13:00)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Tariq Al-Hashimi',
    doctorRole: 'Clinical Director',
    productsDetailed: ['RENALOF 150 ml', 'ASBRIP 150 ml'],
    doctorSentiment: 'Enthusiastic',
    samplesDropped: 2,
    sampleProduct: 'RENALOF 150 ml',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Promote 150ml clinical surgery packs for hospitalized nephrology canine patients',
    outcome: 'Presented clinical trial results. Dr. Tariq agreed to evaluate with inpatient ward team.',
    nextFollowUp: '2026-09-08',
    nextFollowUpPurpose: 'Collect surgery feedback'
  },
  {
    id: 'VIS-2026-0902-01',
    repId: 'T1',
    clientCode: 'DC0623',
    clientName: 'PETS HAVEN VET CLINIC',
    location: 'Dubai',
    date: '2026-09-02',
    timeSlot: 'Morning (10:00 - 11:30)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Chloe Bennett',
    doctorRole: 'Senior Vet Surgeon',
    productsDetailed: ['VIUSID 30 ml', 'ASBRIP 30 ml'],
    doctorSentiment: 'Enthusiastic',
    samplesDropped: 2,
    sampleProduct: 'VIUSID 30 ml',
    orderPlaced: true,
    orderRef: 'ORD-2026-0903-HIST',
    orderValueAed: 850,
    purpose: 'Seasonal immunity campaign detailing for post-boarding recovery animals',
    outcome: 'Doctor placed immediate stocking order for 15 Viusid + 3 FOC and 10 Asbrip 30ml.',
    nextFollowUp: '2026-09-22',
    nextFollowUpPurpose: 'Routine stock review'
  },
  {
    id: 'VIS-2026-0902-02-UNP',
    repId: 'T1',
    clientCode: 'DC0931',
    clientName: 'PETLAND WELLNESS VETERINARY CLINIC',
    location: 'Dubai',
    date: '2026-09-02',
    timeSlot: 'Afternoon Spontaneous (14:00 - 15:00)',
    visitCategory: 'Unplanned',
    unplannedReason: 'Spontaneous Nearby Drop-in',
    status: 'Completed',
    doctorName: 'Dr. Marcus Vance',
    doctorRole: 'Head Veterinarian',
    productsDetailed: ['CARMINAL 30 ml'],
    doctorSentiment: 'Positive',
    samplesDropped: 1,
    sampleProduct: 'CARMINAL 30 ml',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Unplanned visit on route to introduce activated anti-spasmodic veterinary portfolio',
    outcome: 'Dr. Marcus interested in chronic gastritis clinical cases. Sample accepted for outpatient trial.',
    nextFollowUp: '2026-09-20',
    nextFollowUpPurpose: 'Check patient response'
  },
  {
    id: 'VIS-2026-0903-01',
    repId: 'T1',
    clientCode: 'AC0310',
    clientName: 'CANADIAN VETERINARY CLINIC - AL MEENA',
    location: 'Abu Dhabi',
    date: '2026-09-03',
    timeSlot: 'Morning Round (10:30 - 12:00)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Andrew Clarke',
    doctorRole: 'Chief Veterinary Officer',
    productsDetailed: ['VIRULYS Paste 30ml', 'RENALOF 30 ml'],
    doctorSentiment: 'Positive',
    samplesDropped: 2,
    sampleProduct: 'VIRULYS Paste 30ml',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'VIRULYS introduction and renal oxalate dissolution detailing',
    outcome: 'Constructive discussion. Dr. Andrew scheduled second round with senior feline ward nurses.',
    nextFollowUp: '2026-09-08',
    nextFollowUpPurpose: 'Ward team demo'
  },
  {
    id: 'VIS-2026-0903-02',
    repId: 'T1',
    clientCode: 'AC0550',
    clientName: 'CAPITAL VET CLINIC',
    location: 'Abu Dhabi',
    date: '2026-09-03',
    timeSlot: 'Afternoon (14:30 - 16:00)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Fatima Al-Hosani',
    doctorRole: 'Managing Partner',
    productsDetailed: ['ASBRIP 30 ml', 'VIUSID 30 ml'],
    doctorSentiment: 'Neutral',
    samplesDropped: 1,
    sampleProduct: 'ASBRIP 30 ml',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Present cough relief and viral bronchitis recovery portfolio',
    outcome: 'Doctor requested comparative study with conventional ambroxol syrups.',
    nextFollowUp: '2026-09-24',
    nextFollowUpPurpose: 'Deliver comparative papers'
  },
  {
    id: 'VIS-2026-0904-01',
    repId: 'T1',
    clientCode: 'AC0720',
    clientName: 'GERMAN VETERINARY CLINIC',
    location: 'Abu Dhabi',
    date: '2026-09-04',
    timeSlot: 'Morning (10:00 - 11:30)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Katja Lang',
    doctorRole: 'Senior Surgeon & Director',
    productsDetailed: ['VIRULYS Paste 30ml', 'ASBRIP 150 ml'],
    doctorSentiment: 'Enthusiastic',
    samplesDropped: 1,
    sampleProduct: 'VIRULYS Paste 30ml',
    orderPlaced: true,
    orderRef: 'ORD-2026-0904-HIST',
    orderValueAed: 1200,
    purpose: 'Feline upper respiratory tract infections clinical protocol detailing',
    outcome: 'High acceptance. Dr. Katja authorized clinical clinic package order of 20 Virulys + 10 Asbrip 150ml.',
    nextFollowUp: '2026-09-25',
    nextFollowUpPurpose: 'Clinical case study collection'
  },
  {
    id: 'VIS-2026-0907-01',
    repId: 'T1',
    clientCode: 'NC1001',
    clientName: 'ZOOVET VETERINARY CLINIC',
    location: 'Al Ain',
    date: '2026-09-07',
    timeSlot: 'Morning (10:30 - 12:00)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Khalid Mansoor',
    doctorRole: 'Lead Veterinarian',
    productsDetailed: ['VIUSID 30 ml', 'CARMINAL 30 ml'],
    doctorSentiment: 'Positive',
    samplesDropped: 1,
    sampleProduct: 'VIUSID 30 ml',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Al Ain territory field day: introduce activated antioxidant range',
    outcome: 'Presented clinical benefits of molecular activation. Doctor scheduled formal order review for end of month.',
    nextFollowUp: '2026-09-28',
    nextFollowUpPurpose: 'End of month booking'
  },
  {
    id: 'VIS-2026-0907-02-UNP',
    repId: 'T1',
    clientCode: 'NC0406',
    clientName: 'JABAL ALADHAM VETERINARY CLINIC',
    location: 'Al Ain',
    date: '2026-09-07',
    timeSlot: 'Afternoon Spontaneous (13:30 - 14:45)',
    visitCategory: 'Unplanned',
    unplannedReason: 'Spontaneous Nearby Drop-in',
    status: 'Completed',
    doctorName: 'Dr. Sultan Al-Ketbi',
    doctorRole: 'Clinic Owner',
    productsDetailed: ['VIRULYS Paste 30ml', 'BARD Clever Fungus Dermasine 100ml'],
    doctorSentiment: 'Enthusiastic',
    samplesDropped: 1,
    sampleProduct: 'BARD Clever Fungus Dermasine 100ml',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Spontaneous call following Zoovet visit to expand Al Ain clinic reach',
    outcome: 'Excellent response from Dr. Sultan. High demand for skin and dermatological natural solutions.',
    nextFollowUp: '2026-09-28',
    nextFollowUpPurpose: 'Follow up with pharmacy manager'
  },
  {
    id: 'VIS-2026-0908-01',
    repId: 'T1',
    clientCode: 'DC0461',
    clientName: 'NOBLE VETERINARY CLINIC DIP',
    location: 'Dubai',
    date: '2026-09-08',
    timeSlot: 'Morning Follow-up (09:30 - 11:00)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Tariq Al-Hashimi',
    doctorRole: 'Clinical Director',
    productsDetailed: ['RENALOF 30 ml', 'VIRULYS Paste 30ml'],
    doctorSentiment: 'Enthusiastic',
    samplesDropped: 0,
    sampleProduct: '',
    orderPlaced: true,
    orderRef: 'ORD-2026-0908-HIST',
    orderValueAed: 940,
    purpose: 'Second planned cycle call following September 1st hospital trial',
    outcome: 'Follow-up success. Inpatient ward team approved Renalof protocol. Booked 15 Renalof 30ml + 10 Virulys.',
    nextFollowUp: '2026-09-29',
    nextFollowUpPurpose: 'Monthly re-order review'
  },
  {
    id: 'VIS-2026-0908-02',
    repId: 'T1',
    clientCode: 'AC0310',
    clientName: 'CANADIAN VETERINARY CLINIC - AL MEENA',
    location: 'Abu Dhabi',
    date: '2026-09-08',
    timeSlot: 'Afternoon Round (14:00 - 15:30)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Andrew Clarke',
    doctorRole: 'Chief Veterinary Officer',
    productsDetailed: ['VIUSID 30 ml', 'VIRULYS Paste 30ml'],
    doctorSentiment: 'Positive',
    samplesDropped: 1,
    sampleProduct: 'VIUSID 30 ml',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Second cycle call to deliver promised clinical trials to veterinary nursing department',
    outcome: 'Nurses briefed on Virulys palatability in hospitalized cats. Order expected in October cycle.',
    nextFollowUp: '2026-10-06',
    nextFollowUpPurpose: 'October monthly order'
  },

  // ================= T2 (Marsel) September Historical Visits =================
  {
    id: 'VIS-2026-0901-03',
    repId: 'T2',
    clientCode: 'FC0852',
    clientName: 'LOVELY PET CLINIC',
    location: 'Sharjah',
    date: '2026-09-01',
    timeSlot: 'Morning (10:00 - 11:30)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Maria Santos',
    doctorRole: 'Senior Vet Surgeon',
    productsDetailed: ['VIRULYS Paste 30ml', 'BARD Clever Fungus Dermasine 100ml'],
    doctorSentiment: 'Positive',
    samplesDropped: 2,
    sampleProduct: 'VIRULYS Paste 30ml',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Kick-off September cycle: introduce feline herpes protocol and BARD biological spray',
    outcome: 'Dr. Maria requested clinical feedback from other clinics in UAE before adopting.',
    nextFollowUp: '2026-09-06',
    nextFollowUpPurpose: 'Follow-up with Dubai equine & small animal testimonials'
  },
  {
    id: 'VIS-2026-0902-03',
    repId: 'T2',
    clientCode: 'SC0933',
    clientName: 'PETS VETERINARY CLINIC',
    location: 'Sharjah',
    date: '2026-09-02',
    timeSlot: 'Morning (10:30 - 12:00)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Samah Mansi',
    doctorRole: 'Director',
    productsDetailed: ['ASBRIP 30 ml', 'VIUSID 30 ml'],
    doctorSentiment: 'Enthusiastic',
    samplesDropped: 1,
    sampleProduct: 'ASBRIP 30 ml',
    orderPlaced: true,
    orderRef: 'ORD-2026-0902-T2',
    orderValueAed: 720,
    purpose: 'Discuss respiratory support in juvenile kittens and boarding animals',
    outcome: 'Placed order for 12 Asbrip 30ml + 2 FOC and 5 Viusid 30ml.',
    nextFollowUp: '2026-09-23',
    nextFollowUpPurpose: 'Check inventory turnover'
  },
  {
    id: 'VIS-2026-0903-03',
    repId: 'T2',
    clientCode: 'RP0236',
    clientName: 'ALNOOR VETERINARY CLINIC',
    location: 'Ras al- Khaimah',
    date: '2026-09-03',
    timeSlot: 'Morning (10:00 - 11:30)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Tariq Al-Nuaimi',
    doctorRole: 'Chief Vet Surgeon',
    productsDetailed: ['VIRULYS Paste 30ml', 'RENALOF 30 ml'],
    doctorSentiment: 'Positive',
    samplesDropped: 1,
    sampleProduct: 'VIRULYS Paste 30ml',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Detailing Virulys and Renalof to RAK lead veterinary hospital',
    outcome: 'Dr. Tariq accepted sample for inpatient clinic ward trial.',
    nextFollowUp: '2026-09-07',
    nextFollowUpPurpose: 'Review trial results'
  },
  {
    id: 'VIS-2026-0903-04-UNP',
    repId: 'T2',
    clientCode: 'RP0896',
    clientName: 'SHAMAL VETERINARY PHARMACY',
    location: 'Ras al- Khaimah',
    date: '2026-09-03',
    timeSlot: 'Afternoon Spontaneous (13:30 - 14:30)',
    visitCategory: 'Unplanned',
    unplannedReason: 'Spontaneous Nearby Drop-in',
    status: 'Completed',
    doctorName: 'Dr. Faisal Al-Zahrani',
    doctorRole: 'Pharmacy Manager',
    productsDetailed: ['BARD Pythie Pets Ear cleaner', 'CARMINAL 30 ml'],
    doctorSentiment: 'Positive',
    samplesDropped: 1,
    sampleProduct: 'BARD Pythie Pets Ear cleaner',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Spontaneous call at nearby pharmacy after Alnoor Clinic visit',
    outcome: 'Introduced Pythium oligandrum biological ear hygiene. Pharmacy manager agreed to stock upon doctor demand.',
    nextFollowUp: '2026-09-24',
    nextFollowUpPurpose: 'Generate clinic pull-through'
  },
  {
    id: 'VIS-2026-0904-02',
    repId: 'T2',
    clientCode: 'JC0804',
    clientName: 'FLUFFY VETERINARY CLINIC FOR PETS',
    location: 'Ajman',
    date: '2026-09-04',
    timeSlot: 'Morning (11:00 - 12:30)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Nour Al-Hassan',
    doctorRole: 'Managing Director',
    productsDetailed: ['VIRULYS Paste 30ml', 'VIUSID 30 ml'],
    doctorSentiment: 'Positive',
    samplesDropped: 2,
    sampleProduct: 'VIRULYS Paste 30ml',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Initial introduction to Dr. Nour for Virulys palatability and efficacy in Persian cats',
    outcome: 'Dr. Nour started testing on shelter rescues with chronic rhinitis.',
    nextFollowUp: '2026-09-09',
    nextFollowUpPurpose: 'Evaluate rescue cat improvements & secure commercial order'
  },
  {
    id: 'VIS-2026-0906-01',
    repId: 'T2',
    clientCode: 'FC0852',
    clientName: 'LOVELY PET CLINIC',
    location: 'Sharjah',
    date: '2026-09-06',
    timeSlot: 'Morning Follow-up (10:00 - 11:15)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Maria Santos',
    doctorRole: 'Senior Vet Surgeon',
    productsDetailed: ['BARD Clever Fungus Dermasine 100ml', 'VIRULYS Paste 30ml'],
    doctorSentiment: 'Enthusiastic',
    samplesDropped: 1,
    sampleProduct: 'BARD Clever Fungus Dermasine 100ml',
    orderPlaced: true,
    orderRef: 'ORD-2026-0906-T2',
    orderValueAed: 825,
    purpose: 'Second cycle call to present clinic testimonials from Dubai and review trial progress',
    outcome: 'Dr. Maria confirmed trial success on stubborn ringworm case. Placed initial booking of 10 Dermasine + 15 Virulys.',
    nextFollowUp: '2026-09-27',
    nextFollowUpPurpose: 'Review re-orders'
  },
  {
    id: 'VIS-2026-0907-03',
    repId: 'T2',
    clientCode: 'RP0236',
    clientName: 'ALNOOR VETERINARY CLINIC',
    location: 'Ras al- Khaimah',
    date: '2026-09-07',
    timeSlot: 'Morning Follow-up (10:00 - 11:30)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Tariq Al-Nuaimi',
    doctorRole: 'Chief Vet Surgeon',
    productsDetailed: ['ASBRIP 150 ml', 'RENALOF 150 ml'],
    doctorSentiment: 'Positive',
    samplesDropped: 0,
    sampleProduct: '',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Second cycle visit to review inpatient feline trial and present 150ml clinical surgery packs',
    outcome: 'Positive feedback on feline tolerance. Dr. Tariq preparing quarterly purchase requisition.',
    nextFollowUp: '2026-09-28',
    nextFollowUpPurpose: 'Collect purchase requisition'
  },
  {
    id: 'VIS-2026-0907-04-UNP',
    repId: 'T2',
    clientCode: 'SC0215',
    clientName: 'AL SHAMS VETERINARY PHARMACY',
    location: 'Sharjah',
    date: '2026-09-07',
    timeSlot: 'Afternoon Spontaneous (14:30 - 15:30)',
    visitCategory: 'Unplanned',
    unplannedReason: 'Spontaneous Nearby Drop-in',
    status: 'Completed',
    doctorName: 'Dr. Bilal Qasim',
    doctorRole: 'Lead Pharmacist',
    productsDetailed: ['CARMINAL 30 ml', 'VIUSID 30 ml'],
    doctorSentiment: 'Positive',
    samplesDropped: 1,
    sampleProduct: 'CARMINAL 30 ml',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Unplanned pharmacy stop while in Sharjah Rolla district',
    outcome: 'Presented Carminal anti-spasmodic veterinary portfolio. Doctor accepted brochure and product sample.',
    nextFollowUp: '2026-09-29',
    nextFollowUpPurpose: 'Check pharmacy prescription demand'
  },
  {
    id: 'VIS-2026-0908-03',
    repId: 'T2',
    clientCode: 'JC0312',
    clientName: 'AJMAN PET HOSPITAL',
    location: 'Ajman',
    date: '2026-09-08',
    timeSlot: 'Morning (10:30 - 12:00)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Ziad Al-Khouly',
    doctorRole: 'Senior Vet Surgeon',
    productsDetailed: ['VIUSID 30 ml', 'ASBRIP 30 ml'],
    doctorSentiment: 'Positive',
    samplesDropped: 1,
    sampleProduct: 'VIUSID 30 ml',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Detailed Viusid antioxidant and Asbrip oral suspension for kennel cough seasonal outbreak',
    outcome: 'Doctor interested in post-surgical recovery applications. Trial sample left.',
    nextFollowUp: '2026-09-09',
    nextFollowUpPurpose: 'Check unplanned follow-up on BARD Ear cleaner'
  },

  // ================= Today's Calls (2026-09-09) =================
  // T1 Planned Visit 1 (Completed)
  {
    id: 'VIS-2026-0909-01',
    repId: 'T1',
    clientCode: 'DC0340',
    clientName: 'DR SAMIR VET CLINIC',
    location: 'Dubai',
    date: '2026-09-09',
    timeSlot: 'Morning Round (09:30 - 11:30)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Samir Al-Khatib',
    doctorRole: 'Lead Veterinarian & Director',
    productsDetailed: ['VIRULYS Paste 30ml', 'VIUSID 30 ml', 'RENALOF 30 ml'],
    doctorSentiment: 'Enthusiastic',
    samplesDropped: 2,
    sampleProduct: 'VIRULYS Paste 30ml',
    orderPlaced: true,
    orderRef: 'ORD-2026-0901',
    orderValueAed: 1953,
    purpose: 'VIRULYS launch detailing & clinical comparison with competitor lysine pastes',
    outcome: 'Dr. Samir trial was extremely positive. Booked 25 units Asbrip + 5 FOC, 10 Viusid + 2 FOC, and 20 Virulys + 4 FOC.',
    nextFollowUp: '2026-09-23',
    nextFollowUpPurpose: 'Review feline viral conjunctivitis case responses'
  },
  // T1 Planned Visit 2 (Pending)
  {
    id: 'VIS-2026-0909-02',
    repId: 'T1',
    clientCode: 'DC0821',
    clientName: 'Petflix Veterinary Clinic LLC',
    location: 'Dubai',
    date: '2026-09-09',
    timeSlot: 'Afternoon Round (14:00 - 16:00)',
    visitCategory: 'Planned',
    status: 'Planned',
    doctorName: 'Dr. Elena Rostova',
    doctorRole: 'Senior Vet Surgeon',
    productsDetailed: ['ASBRIP 150 ml', 'RENALOF 150 ml'],
    doctorSentiment: 'Pending',
    samplesDropped: 0,
    sampleProduct: '',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Present 150ml clinical clinic packs for high-volume boarding dogs & post-op wards',
    outcome: '',
    nextFollowUp: '',
    nextFollowUpPurpose: ''
  },
  // T1 UNPLANNED VISIT submitted on today beside the planned ones!
  {
    id: 'VIS-2026-0909-03-UNP',
    repId: 'T1',
    clientCode: 'DC0050',
    clientName: 'AL FALAH VETERINARY CLINIC',
    location: 'Dubai',
    date: '2026-09-09',
    timeSlot: 'Midday Spontaneous (12:30 - 13:30)',
    visitCategory: 'Unplanned',
    unplannedReason: 'Spontaneous Nearby Drop-in',
    status: 'Completed',
    doctorName: 'Dr. Tariq Mansoor',
    doctorRole: 'Clinic Director / Owner',
    productsDetailed: ['CARMINAL 30 ml', 'VIUSID 30 ml'],
    doctorSentiment: 'Positive',
    samplesDropped: 1,
    sampleProduct: 'CARMINAL 30 ml',
    orderPlaced: true,
    orderRef: 'ORD-2026-0902',
    orderValueAed: 644.7,
    purpose: 'Nearby opportunistic drop-in while in Deira area between scheduled clinic visits',
    outcome: 'Detailed Carminal activated formulation. Doctor placed order for 13 units Carminal + 2 FOC and 3 Viusid.',
    nextFollowUp: '2026-09-25',
    nextFollowUpPurpose: 'Check clinical improvement in canine gastritis cohort'
  },
  // T2 Planned Call for Today (Completed)
  {
    id: 'VIS-2026-0909-04',
    repId: 'T2',
    clientCode: 'JC0804',
    clientName: 'FLUFFY VETERINARY CLINIC FOR PETS',
    location: 'Ajman',
    date: '2026-09-09',
    timeSlot: 'Morning Round (10:00 - 11:30)',
    visitCategory: 'Planned',
    status: 'Completed',
    doctorName: 'Dr. Nour Al-Hassan',
    doctorRole: 'Managing Director',
    productsDetailed: ['VIRULYS Paste 30ml', 'BARD Clever Fungus Dermasine 100ml'],
    doctorSentiment: 'Enthusiastic',
    samplesDropped: 2,
    sampleProduct: 'BARD Clever Fungus Dermasine 100ml',
    orderPlaced: true,
    orderRef: 'ORD-2026-0905',
    orderValueAed: 1664.25,
    purpose: 'Review Virulys monthly movement and introduce BARD biological antifungal protocol',
    outcome: 'Very strong reception. Booked 25 units Virulys + 5 FOC and 10 units Dermasine 100ml + 2 FOC.',
    nextFollowUp: '2026-09-23',
    nextFollowUpPurpose: 'Deliver Arabic patient client guides'
  },
  // T2 UNPLANNED Visit on today beside the planned ones (Completed)
  {
    id: 'VIS-2026-0909-05-UNP',
    repId: 'T2',
    clientCode: 'JC0312',
    clientName: 'AJMAN PET HOSPITAL',
    location: 'Ajman',
    date: '2026-09-09',
    timeSlot: 'Afternoon Spontaneous (14:30 - 15:30)',
    visitCategory: 'Unplanned',
    unplannedReason: 'Spontaneous Nearby Drop-in',
    status: 'Completed',
    doctorName: 'Dr. Ziad Al-Khouly',
    doctorRole: 'Senior Vet Surgeon',
    productsDetailed: ['BARD Pythie Pets Ear cleaner', 'ASBRIP 30 ml'],
    doctorSentiment: 'Positive',
    samplesDropped: 1,
    sampleProduct: 'BARD Pythie Pets Ear cleaner',
    orderPlaced: false,
    orderRef: '',
    orderValueAed: 0,
    purpose: 'Unplanned drop-in across the street after leaving Fluffy Vet Clinic',
    outcome: 'Met Dr. Ziad between surgeries. Introduced BARD Ear Cleaner bio-action. Doctor accepted trial sample.',
    nextFollowUp: '2026-09-24',
    nextFollowUpPurpose: 'Check otitis externa patient results'
  }
];

window.INITIAL_ORDERS = [
  {
    invoiceNumber: 'ORD-2026-0901',
    date: '2026-09-09',
    repId: 'T1',
    repName: 'Shaimaa',
    clientCode: 'DC0340',
    clientName: 'DR SAMIR VET CLINIC',
    location: 'Dubai',
    territory: 'T1',
    approvalStatus: 'Approved',
    approvedBy: 'Dr. Sameh Ageez (Senior Sales Manager)',
    approvedAt: '2026-09-09T10:15:00Z',
    paymentTerms: '30 Days Credit',
    deliveryUrgency: 'Normal (48h)',
    items: [
      { productCode: 'AS030', productName: 'ASBRIP 30 ml', unitPrice: 32, salesQty: 25, focQty: 5, total: 800 },
      { productCode: 'VP030', productName: 'VIUSID 30 ml', unitPrice: 40, salesQty: 10, focQty: 2, total: 400 },
      { productCode: 'VR030', productName: 'VIRULYS Paste 30ml', unitPrice: 33, salesQty: 20, focQty: 4, total: 660 }
    ],
    totalExcVat: 1860,
    vatAmount: 93,
    totalIncVat: 1953
  },
  {
    invoiceNumber: 'ORD-2026-0902',
    date: '2026-09-09',
    repId: 'T1',
    repName: 'Shaimaa',
    clientCode: 'DC0050',
    clientName: 'AL FALAH VETERINARY CLINIC',
    location: 'Dubai',
    territory: 'T1',
    approvalStatus: 'Pending',
    approvedBy: null,
    approvedAt: null,
    paymentTerms: 'Cash on Delivery (COD)',
    deliveryUrgency: 'Express (24h)',
    items: [
      { productCode: 'CA030', productName: 'CARMINAL 30 ml', unitPrice: 38, salesQty: 13, focQty: 2, total: 494 },
      { productCode: 'VP030', productName: 'VIUSID 30 ml', unitPrice: 40, salesQty: 3, focQty: 0, total: 120 }
    ],
    totalExcVat: 614,
    vatAmount: 30.7,
    totalIncVat: 644.7
  },
  {
    invoiceNumber: 'ORD-2026-0905',
    date: '2026-09-09',
    repId: 'T2',
    repName: 'Marsel',
    clientCode: 'JC0804',
    clientName: 'FLUFFY VETERINARY CLINIC FOR PETS',
    location: 'Ajman',
    territory: 'T2',
    approvalStatus: 'Pending',
    approvedBy: null,
    approvedAt: null,
    paymentTerms: '30 Days Credit',
    deliveryUrgency: 'Normal (48h)',
    items: [
      { productCode: 'VR030', productName: 'VIRULYS Paste 30ml', unitPrice: 33, salesQty: 25, focQty: 5, total: 825 },
      { productCode: 'BD0100', productName: 'BARD Clever Fungus Dermasine 100ml', unitPrice: 76, salesQty: 10, focQty: 2, total: 760 }
    ],
    totalExcVat: 1585,
    vatAmount: 79.25,
    totalIncVat: 1664.25
  }
];

window.INITIAL_NOTIFICATIONS = [
  {
    id: 'NOTIF-001',
    type: 'ORDER_SUBMITTED',
    title: 'New Field Sales Order Submitted',
    orderNumber: 'ORD-2026-0902',
    repId: 'T1',
    repName: 'Shaimaa',
    clientCode: 'DC0050',
    clientName: 'AL FALAH VETERINARY CLINIC',
    location: 'Dubai',
    totalExcVat: 614,
    totalIncVat: 644.7,
    timestamp: '2026-09-09T13:35:00Z',
    read: false,
    approvalStatus: 'Pending',
    itemsSummary: 'CARMINAL 30 ml (13 Sls + 2 FOC), VIUSID 30 ml (3 Sls)',
    paymentTerms: 'Cash on Delivery (COD)',
    deliveryUrgency: 'Express (24h)',
    items: [
      { productCode: 'CA030', productName: 'CARMINAL 30 ml', unitPrice: 38, salesQty: 13, focQty: 2, total: 494 },
      { productCode: 'VP030', productName: 'VIUSID 30 ml', unitPrice: 40, salesQty: 3, focQty: 0, total: 120 }
    ]
  },
  {
    id: 'NOTIF-002',
    type: 'ORDER_SUBMITTED',
    title: 'New Field Sales Order Submitted',
    orderNumber: 'ORD-2026-0905',
    repId: 'T2',
    repName: 'Marsel',
    clientCode: 'JC0804',
    clientName: 'FLUFFY VETERINARY CLINIC FOR PETS',
    location: 'Ajman',
    totalExcVat: 1585,
    totalIncVat: 1664.25,
    timestamp: '2026-09-09T11:40:00Z',
    read: false,
    approvalStatus: 'Pending',
    itemsSummary: 'VIRULYS Paste 30ml (25 Sls + 5 FOC), BARD Clever Fungus Dermasine 100ml (10 Sls + 2 FOC)',
    paymentTerms: '30 Days Credit',
    deliveryUrgency: 'Normal (48h)',
    items: [
      { productCode: 'VR030', productName: 'VIRULYS Paste 30ml', unitPrice: 33, salesQty: 25, focQty: 5, total: 825 },
      { productCode: 'BD0100', productName: 'BARD Clever Fungus Dermasine 100ml', unitPrice: 76, salesQty: 10, focQty: 2, total: 760 }
    ]
  }
];

